spring:
    application:
        name: rksp7
    r2dbc:
      url: r2dbc:postgresql://rksp7:rksp7@localhost:5432/rksp7
      username: rksp7
      password: rksp7
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create-drop

server:
  port: 8088

