spring:
  application:
    name: rksp7
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/rksp7
    username: rksp7
    password: rksp7
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/rksp7
    password: rksp7
    user: rksp7

server:
  port: 8088