services:
  postgres:
    container_name: postgres_rsocket
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: rsocket
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres: